name: Deploy blog to Amazon ECS
on:
  push:
    branches: ['master']

jobs:
  build-and-deploy:
    name: build the blog and deploy to Amazon ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # install dependencies
      - name: Install dependencies and build
        run: npm ci && npm run docs:build
        # deploy to Amazon ECS
      - name: Deploy to Amazon ECS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
