name: Vite Github Pages Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  pages: write # to deploy to Pages
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: make a directory
        run: |
          mkdir -p .vitepress/temp/blog
          mv .vitepress/dist/* .vitepress/temp/blog
          find . -maxdepth 1 -type d ! -name . ! -name .git ! -name .github ! -name .vitepress ! -name node_modules  -exec mv {} .vitepress/temp \;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: .vitepress/temp
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

